require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpecialGlobalVars:
  Enabled: false

# Will lean on CodeClimate for these
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
