name: Ruby Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    name: Specs - Ruby ${{ matrix.ruby-version }} ${{matrix.gemfile}}
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: c40b3a4da6b10ebaf517551469ec8a5788c6edff1b869d74b3b36153ed3a9764
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      COVERAGE: true

    strategy:
      matrix:
        gemfile:
          - activerecord6
          - activerecord7
        ruby-version:
          - "3.1"
          - "3.0"
          - "2.7"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
        if: matrix.ruby-version == '3.1' && matrix.gemfile == 'activerecord7'
      - name: Run tests
        run: bundle exec rspec
      - name: Upload Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        if: matrix.ruby-version == '3.1' && matrix.gemfile == 'activerecord7'
